apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: poi
        image: registrytys9109.azurecr.io/poi:1.0
        livenessProbe:
          httpGet:
            path: /api/poi/healthcheck
            port: 80
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/poi/healthcheck
            port: 80
          periodSeconds: 10
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secrets"
          readOnly: true
        env:
        - name: SQL_USER
          value: sqladmintYs9109
        - name: SQL_SERVER
          value: sqlservertys9109.database.windows.net        
        ports:
        - containerPort: 80
          name: poi
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname"
            nodePublishSecretRef:                       # Only required when using service principal mode
              name: secrets-store-creds           
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: back
spec:
  ports:
  - port: 80
  selector:
    app: poi