apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: back
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "ru-openhack-team3-new"
    objects: |
      array:
        - |
          objectName: SQL-PASSWORD              
          objectType: secret
          objectAlias: SQL_PASSWORD
          objectVersion: ""
    tenantId: "117ae3fd-bfe1-4ce5-b27e-938eea54b731"