apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: trips
        image: registrytys9109.azurecr.io/trips:1.0
        livenessProbe:
          httpGet:
            path: /api/trips/healthcheck
            port: 80
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/trips/healthcheck
            port: 80
          periodSeconds: 10
        env:
        - name: SQL_USER
          value: sqladmintYs9109
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: SQL_PASSWORD
        - name: SQL_SERVER
          value: sqlservertys9109.database.windows.net        
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secrets"
          readOnly: true
        ports:
        - containerPort: 80
          name: trips
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname"
          nodePublishSecretRef:                       # Only required when using service principal mode
            name: secrets-store-creds           
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: back
spec:
  ports:
  - port: 80
    name: main
  selector:
    app: trips