apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: tripviewer
        image: registrytys9109.azurecr.io/tripviewer:1.0
        env:
        - name: TRIPS_API_ENDPOINT
          value: http://trips:80
        - name: USERPROFILE_API_ENDPOINT
          value: http://userprofile:80     
        ports:
        - containerPort: 80
          name: tripviewer
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: front
spec:
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
    app: tripviewer